Repository Icinga/icinga-powershell-cluster, pull requests merged in 2023-08, with the labels that each got.

#50 Update Get-IcingaClusterSharedVolumeData.psm1
  doc/31-Changelog.md
  provider/sharedVolume/Get-IcingaClusterSharedVolumeData.psm1
Labels: cla/signed

#51 Feature: Updates config for Icinga 2.14
  config/director/Cluster_Bundle.json
  config/director/Invoke-IcingaCheckClusterHealth.json
  config/director/Invoke-IcingaCheckClusterNetwork.json
  config/director/Invoke-IcingaCheckClusterSharedVolume.json
  config/icinga/Cluster_Bundle.conf
  config/icinga/Invoke-IcingaCheckClusterHealth.conf
  config/icinga/Invoke-IcingaCheckClusterNetwork.conf
  config/icinga/Invoke-IcingaCheckClusterSharedVolume.conf
  doc/10-Icinga-Plugins.md
  doc/31-Changelog.md
  doc/plugins/02-Invoke-IcingaCheckClusterSharedVolume.md
  doc/plugins/03-Invoke-IcingaCheckClusterHealth.md
  icinga-powershell-cluster.psd1
Labels: enhancement, cla/signed

#52 Fix: Broken Icinga plain config
  config/icinga/Cluster_Bundle.conf
  config/icinga/Invoke-IcingaCheckClusterHealth.conf
  config/icinga/Invoke-IcingaCheckClusterNetwork.conf
  config/icinga/Invoke-IcingaCheckClusterSharedVolume.conf
  doc/31-Changelog.md
Labels: bug, cla/signed
